spring.datasource.url=jdbc:mysql://${HOST_DB}:${PORT_DB}/nimagu?useSSL=false
spring.datasource.username=${USER_DB}
spring.datasource.password=${PASSWORD_DB}
server.port=${PORT_SERVER}

// spring.datasource.url=jdbc:mysql://degrosmysql846.c7gcsq2m6c6v.us-east-2.rds.amazonaws.com:3306/nimagu?useSSL=false
// spring.datasource.username=admin
// spring.datasource.password=Juanpa05
// server.port=5000

// logging.level.org.springframework=DEBUG
// logging.level.com.Sisbul=DEBUG
FRONTEND_URL=${FRONTEND_URL}

